# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 00:18
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capim',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Capim.upload_dir, verbose_name='Imagem'),
        ),
    ]
