# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170325_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='capim',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capim',
            name='data_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
